### ISSUE TITLE
SDK Node.js & Docker: ECONNREFUSED 127.0.0.1:51024

### ISSUE THREAD

**Issue by simon-tannai** [microsoft/botframework-sdk#5587]
Hello !

I'm trying to push a bot built with Node.js Botframework SDK v4. 
The bot is starting up and when I'm sending a first message with Bot Framework SDK, I get this error: `ECONNREFUSED 127.0.0.1:51024`

The stack:
```
Error: connect ECONNREFUSED 127.0.0.1:51024
    at new RestError (/usr/src/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1397:28)
    at AxiosHttpClient.<anonymous> (/usr/src/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1550:35)
    at step (/usr/src/node_modules/tslib/tslib.js:136:27)
    at Object.throw (/usr/src/node_modules/tslib/tslib.js:117:57)
    at rejected (/usr/src/node_modules/tslib/tslib.js:108:69)
    at process._tickCallback (internal/process/next_tick.js:68:7)
BotFrameworkAdapter.processActivity(): 500 ERROR - Error: connect ECONNREFUSED 127.0.0.1:51024
(node:44) UnhandledPromiseRejectionWarning: Error: Error: connect ECONNREFUSED 127.0.0.1:51024
    at BotFrameworkAdapter.processActivity (/usr/src/node_modules/botbuilder/lib/botFrameworkAdapter.js:511:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

What is this `51024` port ?

**Comment by mdrichardson** [comment]
@simon-tannai 	Looks like your bot is trying to start listening at `127.0.0.1:51024` but the port is probably in use by something else.

Can you provide steps to reproduce? That's not the standard Bot Framework port number (`:3978`).

As you're running this in docker, you may need to expose the port when starting the container with something like:

```bash
docker run -d -p 51024:51204
```

**Comment by tsuwandy** [comment]
@simon-tannai, thanks for reporting.  Are you seeing this in the Emulator?   Could you hit the bot endpoint directly via postman?  We'll also get someone from Support team to help.

**Comment by simon-tannai** [comment]
@mdrichardson I'm using Dockerfile and Docker Compose. My bot is listening on port `3978`.

Dockerfile:
```
# Build step
FROM node:10.16 AS cm-botframework-prebuild

# Create future workdir
RUN mkdir -p /usr/src

# Define workdir
WORKDIR /usr/src

# Copy sources files
COPY ./dialogs /usr/src/dialogs
COPY ./.env /usr/src/.env
COPY ./bot.js /usr/src/bot.js
COPY ./index.js /usr/src/index.js
COPY ./package.json /usr/src/package.json
COPY ./package-lock.json /usr/src/package-lock.json

# Install dependencies
RUN npm i

###################################################################

# Final step
FROM node:10.16

# Get files from build step
COPY --from=cm-botframework-prebuild /usr/src /usr/src

# Define bot as workdir
WORKDIR /usr/src

# Expose bot port
EXPOSE 3978
```

Docker compose:
```
cm-botframework-bot:
    build:
      context: ./../bot-server
      dockerfile: ./Dockerfile
    container_name: cm-botframework-bot
    command: npm run watch
    volumes:
      - ./../bot-server/dialogs:/usr/src/dialogs
      - ./../bot-server/.env:/usr/src/.env
      - ./../bot-server/bot.js:/usr/src/bot.js
      - ./../bot-server/index.js:/usr/src/index.js
      - ./../bot-server/package.json:/usr/src/package.json
      - ./../bot-server/package-lock.json:/usr/src/package-lock.json
    ports:
      - 3978:3978
    networks:
      cm-botframework:
        aliases:
          - cm-botframework-bot
```

From Postman, a simple POST request on `http://127.0.0.1:3978/api/messages` is working. 

But through Bot Framework Emulator, it still not working. The port changed for `http://localhost:50073`. It seems the bot tried to reply to the Emulator on localhost. His request was not go outside of Docker's virtual network. 

I tested with [Ngrok tunneling](https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok)) and it's working fine. 

I don't know if it's possible to "force" a localhost request from Docker's container to hit on host machine :S
