### ISSUE TITLE
ERROR in ./node_modules/botframework-webchat/lib/speech/CustomAudioInputStream.js 40:39-61

### ISSUE THREAD

**Issue by jenkoc** [microsoft/botframework-sdk#6452]
## Version
4.12.2

## Describe the bug
When running `npm run dev` `npm run hot` `npm run prod` i am getting the following error: 
```
ERROR in ./node_modules/botframework-webchat/lib/speech/CustomAudioInputStream.js 40:39-61
Module not found: Error: Can't resolve 'p-defer-es5' in 'C:\Sources\Bot\CosmoConsultBot\CosmoBot\node_modules\botframework-webchat\lib\speech'

webpack compiled with 1 error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cosmo-bot@1.0.0 development: `npx mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cosmo-bot@1.0.0 development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

## Additional context
I've already tried to run `npm audit fix`. I can't realy reproduce the issue. Sometime npm run runs w/o any error. Our build pipeline also now fails with this error. 

## package.json

```{
  "name": "cosmo-bot",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "npm run development",
    "development": "npx mix",
    "watch": "npx mix watch",
    "hot": "npx mix watch --hot",
    "prod": "npm run production",
    "production": "npx mix --production"
  },
  "author": "",
  "license": "",
  "private": true,
  "devDependencies": {
    "@babel/preset-react": "^7.13.13",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.0-beta.0",
    "@typescript-eslint/eslint-plugin": "^4.22.0",
    "@typescript-eslint/parser": "^4.22.0",
    "eslint": "^7.24.0",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "laravel-mix": "^6.0.13",
    "laravel-mix-polyfill": "^3.0.0",
    "node-libs-browser": "^2.2.1",
    "postcss": "^8.2.9",
    "prettier": "2.2.1",
    "react-refresh": "^0.10.0",
    "resolve-url-loader": "^3.1.2",
    "sass": "^1.32.8",
    "sass-loader": "^10.1.1",
    "ts-loader": "^8.1.0",
    "typescript": "^4.2.3"
  },
  "dependencies": {
    "@fluentui/react": "^8.8.0",
    "@fluentui/react-charting": "^5.3.31",
    "@types/jquery": "^3.5.5",
    "@types/lodash": "^4.14.170",
    "@types/prosemirror-commands": "^1.0.4",
    "@types/prosemirror-dropcursor": "^1.0.1",
    "@types/prosemirror-gapcursor": "^1.0.3",
    "@types/prosemirror-history": "^1.0.2",
    "@types/prosemirror-inputrules": "^1.0.4",
    "@types/prosemirror-keymap": "^1.0.4",
    "@types/prosemirror-markdown": "^1.5.1",
    "@types/prosemirror-menu": "^1.0.3",
    "@types/prosemirror-model": "^1.13.0",
    "@types/prosemirror-schema-basic": "^1.0.2",
    "@types/prosemirror-state": "^1.2.6",
    "@types/prosemirror-view": "^1.17.1",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "@types/react-router-dom": "^5.1.7",
    "axios": "^0.21.1",
    "botframework-webchat": "^4.12.1",
    "jquery": "^3.6.0",
    "jquery-ui": "^1.12.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "prosemirror-example-setup": "^1.1.2",
    "prosemirror-image-uploader": "^1.0.0",
    "prosemirror-markdown": "^1.5.1",
    "prosemirror-model": "^1.14.0",
    "prosemirror-schema-basic": "^1.1.2",
    "prosemirror-state": "^1.3.4",
    "prosemirror-view": "^1.18.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hook-form": "^7.11.0",
    "react-ios-pwa-prompt": "^1.8.4",
    "react-moment": "^1.1.1",
    "react-query": "^3.17.2",
    "react-router-dom": "^5.2.0",
    "select2": "^4.0.13",
    "use-prosemirror": "^1.2.1"
  }
}
```

**Comment by stevkan** [comment]
@jenkoc, can you tell me:

- Which version of node you have installed?
- Which version of Web Chat are you using? You list v4.12.2, but that version doesn't exist for Web Chat so I'm assuming that is for the SDK...?
- Do you have speech configured for use in Web Chat, at all?
- Does this occur across browsers or only in one browser (Chrome, Edge, etc.)?
- Are you able to share your code (minus any keys/secrets) for me to attempt a repro with? Or, at a minimum, the file that is instantiating Web Chat and any associated code/files?

**Comment by jenkoc** [comment]
@stevkan thanks for your quick response.

- Node Version v16.13.2
- Webchat Version 4.14.1
- _Do you have speech configured for use in Web Chat, at all?_ => No
- _Does this occur across browsers or only in one browser (Chrome, Edge, etc.)?_ => The error occurs during the build process not in the browser
- You can find a simple repo where I tried to reproduce the error [here](https://github.com/jenkoc/webchat-bug-repro). Unfortunally we weren't able to consistently reproduce the exact same error locally (for some reason the error only occurs randomly). However, with the following yaml you can create a Azure DevOps Pipeline that will consistently throw a related error that we were also experiencing. Even after extensive debugging we don't know how to consistently reproduce the error.

We hope you can help us with this evasive error (even if we can't provide exact reproduction steps) since it is causing delays during our development. Feel free to let us know if you need more information from us or if there is some way we can help.


# Azure DevOps Pipeline
```yaml
trigger:
  branches:
    include:
    - refs/heads/*
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Phase_1
  displayName: Build and Publish Artifact
  timeoutInMinutes: 0
  pool:
    name: Hosted VS2017
  steps:
  - checkout: self
    clean: true
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: node -v && npm -v
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: .
      verbose: false
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      workingDir: .
      verbose: false
      customCommand: run build
...
```
